import '../models/day.dart';

// List of days shown in Search Screen horizontal slider
List<Day> days = [
  Day(name: '木', date: '26'),
  Day(name: '金', date: '27'),
  Day(name: '土', date: '28'),
  Day(name: '日', date: '29'),
  Day(name: '月', date: '30'),
  Day(name: '火', date: '31'),
  Day(name: '水', date: '1'),
  Day(name: '木', date: '2'),
  Day(name: '金', date: '3'),
  Day(name: '土', date: '4'),
  Day(name: '日', date: '5'),
  Day(name: '月', date: '6'),
  Day(name: '火', date: '7'),
  Day(name: '水', date: '8'),
  Day(name: '木', date: '9'),
  Day(name: '金', date: '10'),
  Day(name: '土', date: '11'),
  Day(name: '日', date: '12'),
  Day(name: '月', date: '13'),
  Day(name: '火', date: '14'),
  Day(name: '水', date: '15'),
  Day(name: '木', date: '16'),
  Day(name: '金', date: '17'),
  Day(name: '土', date: '18'),
  Day(name: '日', date: '19'),
  Day(name: '月', date: '20'),
  Day(name: '火', date: '21'),
  Day(name: '水', date: '22'),
  Day(name: '木', date: '23'),
  Day(name: '金', date: '24'),
  Day(name: '土', date: '25'),
];
